<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mvvm\**" />
    <EmbeddedResource Remove="Mvvm\**" />
    <None Remove="Mvvm\**" />
    <Page Remove="Mvvm\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="taglib" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\vinyl.ico" />
    <None Remove="Resources\vinyl.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\vinyl.ico" />
    <Resource Include="Resources\vinyl.png" />
  </ItemGroup>

</Project>
